/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import Tickets.ControladorTickets;
import Tickets.TipoTicket;

/**
 *
 * @author Student
 */
public class FrmAtencion extends javax.swing.JInternalFrame {

    private ControladorTickets controlador;

    /**
     * Creates new form FrmAtencion
     *
     * @param controlador
     */
    public FrmAtencion(ControladorTickets controlador) {
        initComponents();
        this.controlador = controlador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTipo = new javax.swing.JComboBox<>();
        btnAtender = new javax.swing.JButton();

        setClosable(true);
        setTitle("Antencion");

        txtTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Preferencial", "Plataforma", "Caja" }));
        txtTipo.setSelectedIndex(-1);

        btnAtender.setText("Siguiente");
        btnAtender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtenderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTipo, 0, 108, Short.MAX_VALUE)
                    .addComponent(btnAtender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAtender)
                .addContainerGap(189, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtenderActionPerformed
        TipoTicket tipo;
        switch (this.txtTipo.getSelectedIndex()) {
            case 0 -> {
                tipo = TipoTicket.Preferencial;
            }
            case 1 -> {
                tipo = TipoTicket.Plataformas;
            }
            case 2 -> {
                tipo = TipoTicket.cajas;
            }
            default -> {
                tipo = TipoTicket.Preferencial;
            }
        }
        controlador.atender(tipo);
    }//GEN-LAST:event_btnAtenderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtender;
    private javax.swing.JComboBox<String> txtTipo;
    // End of variables declaration//GEN-END:variables
}
